// Script para fusionar y agregar 100+ canciones de K-Pop al catálogo de siembra global
import fs from "fs";
import path from "path";

const seed500Path = path.resolve("scratch/seed_500_songs.js");

const kpopSongs = [
  { title: "Dynamite", artist: "BTS", genre: "Kpop" },
  { title: "Butter", artist: "BTS", genre: "Kpop" },
  { title: "Boy With Luv", artist: "BTS x Halsey", genre: "Kpop" },
  { title: "Fake Love", artist: "BTS", genre: "Kpop" },
  { title: "DNA", artist: "BTS", genre: "Kpop" },
  { title: "Idol", artist: "BTS", genre: "Kpop" },
  { title: "Mic Drop", artist: "BTS x Steve Aoki", genre: "Kpop" },
  { title: "Spring Day", artist: "BTS", genre: "Kpop" },
  { title: "Blood Sweat & Tears", artist: "BTS", genre: "Kpop" },
  { title: "Run BTS", artist: "BTS", genre: "Kpop" },
  { title: "How You Like That", artist: "BLACKPINK", genre: "Kpop" },
  { title: "Kill This Love", artist: "BLACKPINK", genre: "Kpop" },
  { title: "DDU-DU DDU-DU", artist: "BLACKPINK", genre: "Kpop" },
  { title: "Pink Venom", artist: "BLACKPINK", genre: "Kpop" },
  { title: "Shut Down", artist: "BLACKPINK", genre: "Kpop" },
  { title: "As If It's Your Last", artist: "BLACKPINK", genre: "Kpop" },
  { title: "Boombayah", artist: "BLACKPINK", genre: "Kpop" },
  { title: "Lovesick Girls", artist: "BLACKPINK", genre: "Kpop" },
  { title: "Playing with Fire", artist: "BLACKPINK", genre: "Kpop" },
  { title: "Whistle", artist: "BLACKPINK", genre: "Kpop" },
  { title: "Fancy", artist: "TWICE", genre: "Kpop" },
  { title: "What Is Love?", artist: "TWICE", genre: "Kpop" },
  { title: "TT", artist: "TWICE", genre: "Kpop" },
  { title: "Feel Special", artist: "TWICE", genre: "Kpop" },
  { title: "I Can't Stop Me", artist: "TWICE", genre: "Kpop" },
  { title: "The Feels", artist: "TWICE", genre: "Kpop" },
  { title: "Alcohol-Free", artist: "TWICE", genre: "Kpop" },
  { title: "Cheer Up", artist: "TWICE", genre: "Kpop" },
  { title: "Likey", artist: "TWICE", genre: "Kpop" },
  { title: "Talk that Talk", artist: "TWICE", genre: "Kpop" },
  { title: "Hype Boy", artist: "NewJeans", genre: "Kpop" },
  { title: "Ditto", artist: "NewJeans", genre: "Kpop" },
  { title: "OMG", artist: "NewJeans", genre: "Kpop" },
  { title: "Super Shy", artist: "NewJeans", genre: "Kpop" },
  { title: "Attention", artist: "NewJeans", genre: "Kpop" },
  { title: "Cookie", artist: "NewJeans", genre: "Kpop" },
  { title: "ETA", artist: "NewJeans", genre: "Kpop" },
  { title: "How Sweet", artist: "NewJeans", genre: "Kpop" },
  { title: "Bubble Gum", artist: "NewJeans", genre: "Kpop" },
  { title: "God's Menu", artist: "Stray Kids", genre: "Kpop" },
  { title: "S-Class", artist: "Stray Kids", genre: "Kpop" },
  { title: "Maniac", artist: "Stray Kids", genre: "Kpop" },
  { title: "Thunderous", artist: "Stray Kids", genre: "Kpop" },
  { title: "Case 143", artist: "Stray Kids", genre: "Kpop" },
  { title: "Back Door", artist: "Stray Kids", genre: "Kpop" },
  { title: "LALALALA", artist: "Stray Kids", genre: "Kpop" },
  { title: "Super", artist: "SEVENTEEN", genre: "Kpop" },
  { title: "Don't Wanna Cry", artist: "SEVENTEEN", genre: "Kpop" },
  { title: "Hot", artist: "SEVENTEEN", genre: "Kpop" },
  { title: "Very Nice (Aju Nice)", artist: "SEVENTEEN", genre: "Kpop" },
  { title: "Left & Right", artist: "SEVENTEEN", genre: "Kpop" },
  { title: "Maestro", artist: "SEVENTEEN", genre: "Kpop" },
  { title: "Love Shot", artist: "EXO", genre: "Kpop" },
  { title: "Growl", artist: "EXO", genre: "Kpop" },
  { title: "Monster", artist: "EXO", genre: "Kpop" },
  { title: "Call Me Baby", artist: "EXO", genre: "Kpop" },
  { title: "Tempo", artist: "EXO", genre: "Kpop" },
  { title: "Red Flavor", artist: "Red Velvet", genre: "Kpop" },
  { title: "Psycho", artist: "Red Velvet", genre: "Kpop" },
  { title: "Bad Boy", artist: "Red Velvet", genre: "Kpop" },
  { title: "Feel My Rhythm", artist: "Red Velvet", genre: "Kpop" },
  { title: "Queendom", artist: "Red Velvet", genre: "Kpop" },
  { title: "Wannabe", artist: "ITZY", genre: "Kpop" },
  { title: "Dalla Dalla", artist: "ITZY", genre: "Kpop" },
  { title: "Loco", artist: "ITZY", genre: "Kpop" },
  { title: "Not Shy", artist: "ITZY", genre: "Kpop" },
  { title: "Sneakers", artist: "ITZY", genre: "Kpop" },
  { title: "Love Dive", artist: "IVE", genre: "Kpop" },
  { title: "Eleven", artist: "IVE", genre: "Kpop" },
  { title: "After LIKE", artist: "IVE", genre: "Kpop" },
  { title: "I AM", artist: "IVE", genre: "Kpop" },
  { title: "Baddie", artist: "IVE", genre: "Kpop" },
  { title: "Next Level", artist: "aespa", genre: "Kpop" },
  { title: "Black Mamba", artist: "aespa", genre: "Kpop" },
  { title: "Savage", artist: "aespa", genre: "Kpop" },
  { title: "Spicy", artist: "aespa", genre: "Kpop" },
  { title: "Drama", artist: "aespa", genre: "Kpop" },
  { title: "Supernova", artist: "aespa", genre: "Kpop" },
  { title: "Armageddon", artist: "aespa", genre: "Kpop" },
  { title: "Fearless", artist: "LE SSERAFIM", genre: "Kpop" },
  { title: "Antifragile", artist: "LE SSERAFIM", genre: "Kpop" },
  { title: "Unforgiven", artist: "LE SSERAFIM", genre: "Kpop" },
  { title: "Eve, Psyche & The Bluebeard's Wife", artist: "LE SSERAFIM", genre: "Kpop" },
  { title: "Easy", artist: "LE SSERAFIM", genre: "Kpop" },
  { title: "Smart", artist: "LE SSERAFIM", genre: "Kpop" },
  { title: "TOMBOY", artist: "(G)I-DLE", genre: "Kpop" },
  { title: "Nxde", artist: "(G)I-DLE", genre: "Kpop" },
  { title: "Queencard", artist: "(G)I-DLE", genre: "Kpop" },
  { title: "Super Lady", artist: "(G)I-DLE", genre: "Kpop" },
  { title: "Fate", artist: "(G)I-DLE", genre: "Kpop" },
  { title: "Crown", artist: "TXT", genre: "Kpop" },
  { title: "Blue Hour", artist: "TXT", genre: "Kpop" },
  { title: "Sugar Rush Ride", artist: "TXT", genre: "Kpop" },
  { title: "Deja Vu", artist: "TXT", genre: "Kpop" },
  { title: "Fever", artist: "ENHYPEN", genre: "Kpop" },
  { title: "Bite Me", artist: "ENHYPEN", genre: "Kpop" },
  { title: "Polaroid Love", artist: "ENHYPEN", genre: "Kpop" },
  { title: "Sweet Venom", artist: "ENHYPEN", genre: "Kpop" },
  { title: "Bang Bang Bang", artist: "BIGBANG", genre: "Kpop" },
  { title: "Fantastic Baby", artist: "BIGBANG", genre: "Kpop" },
  { title: "Haru Haru", artist: "BIGBANG", genre: "Kpop" },
  { title: "Gee", artist: "Girls' Generation (SNSD)", genre: "Kpop" },
  { title: "The Boys", artist: "Girls' Generation (SNSD)", genre: "Kpop" },
  { title: "Lilac", artist: "IU", genre: "Kpop" },
  { title: "Good Day", artist: "IU", genre: "Kpop" },
  { title: "Blueming", artist: "IU", genre: "Kpop" },
  { title: "Eight", artist: "IU x SUGA", genre: "Kpop" },
  { title: "Gangnam Style", artist: "PSY", genre: "Kpop" },
  { title: "Gentleman", artist: "PSY", genre: "Kpop" },
  { title: "That That", artist: "PSY x SUGA", genre: "Kpop" },
  { title: "Ring Ding Dong", artist: "SHINee", genre: "Kpop" },
  { title: "Sherlock", artist: "SHINee", genre: "Kpop" },
  { title: "View", artist: "SHINee", genre: "Kpop" },
  { title: "Sorry, Sorry", artist: "Super Junior", genre: "Kpop" },
  { title: "Mr. Simple", artist: "Super Junior", genre: "Kpop" },
  { title: "BBOOM BBOOM", artist: "MOMOLAND", genre: "Kpop" },
  { title: "DUN DUN", artist: "EVERGLOW", genre: "Kpop" },
  { title: "LA DI DA", artist: "EVERGLOW", genre: "Kpop" },
  { title: "Cupid", artist: "FIFTY FIFTY", genre: "Kpop" },
  { title: "ASAP", artist: "STAYC", genre: "Kpop" },
  { title: "Stereotype", artist: "STAYC", genre: "Kpop" },
  { title: "O.O", artist: "NMIXX", genre: "Kpop" },
  { title: "Love Me Like This", artist: "NMIXX", genre: "Kpop" },
  { title: "Get A Guitar", artist: "RIIZE", genre: "Kpop" },
  { title: "Love 119", artist: "RIIZE", genre: "Kpop" },
  { title: "Plot Twist", artist: "TWS", genre: "Kpop" },
  { title: "Magnetic", artist: "ILLIT", genre: "Kpop" },
  { title: "Sheesh", artist: "BABYMONSTER", genre: "Kpop" },
  { title: "Batter Up", artist: "BABYMONSTER", genre: "Kpop" },
  { title: "I Am The Best", artist: "2NE1", genre: "Kpop" },
  { title: "Fire", artist: "2NE1", genre: "Kpop" },
  { title: "Nobody", artist: "Wonder Girls", genre: "Kpop" },
  { title: "Bad Girl Good Girl", artist: "Miss A", genre: "Kpop" },
  { title: "Move", artist: "Taemin", genre: "Kpop" },
  { title: "Guilty", artist: "Taemin", genre: "Kpop" },
  { title: "Daechwita", artist: "Agust D", genre: "Kpop" },
  { title: "Haegeum", artist: "Agust D", genre: "Kpop" },
  { title: "On The Street", artist: "J-Hope x J. Cole", genre: "Kpop" },
  { title: "Like Crazy", artist: "Jimin", genre: "Kpop" },
  { title: "Seven", artist: "Jungkook x Latto", genre: "Kpop" },
  { title: "3D", artist: "Jungkook x Jack Harlow", genre: "Kpop" },
  { title: "Standing Next to You", artist: "Jungkook", genre: "Kpop" },
  { title: "Love Me Again", artist: "V", genre: "Kpop" },
  { title: "Slow Dancing", artist: "V", genre: "Kpop" },
  { title: "The Astronaut", artist: "Jin", genre: "Kpop" },
  { title: "Wild Flower", artist: "RM", genre: "Kpop" },
  { title: "On The Ground", artist: "Rose", genre: "Kpop" },
  { title: "Gone", artist: "Rose", genre: "Kpop" },
  { title: "Lalisa", artist: "Lisa", genre: "Kpop" },
  { title: "Money", artist: "Lisa", genre: "Kpop" },
  { title: "Solo", artist: "Jennie", genre: "Kpop" },
  { title: "You & Me", artist: "Jennie", genre: "Kpop" },
  { title: "Flower", artist: "Jisoo", genre: "Kpop" },
  { title: "Gashina", artist: "Sunmi", genre: "Kpop" },
  { title: "Roller Coaster", artist: "Chungha", genre: "Kpop" },
  { title: "Dumb Dumb", artist: "Somi", genre: "Kpop" },
  { title: "What You Waiting For", artist: "Somi", genre: "Kpop" },
  { title: "Zoom", artist: "Jessi", genre: "Kpop" },
  { title: "Nunu Nana", artist: "Jessi", genre: "Kpop" },
  { title: "Mommae", artist: "Jay Park", genre: "Kpop" }
];

async function run() {
  console.log("=== Fusionando y agregando K-Pop ===");
  const seedContent = fs.readFileSync(seed500Path, "utf-8");
  const match = seedContent.match(/const songs = (\[[\s\S]*?\]);/);
  if (!match) {
    console.error("❌ No se encontró el arreglo.");
    return;
  }

  const existingSongs = eval(match[1]);
  const mergedSongs = [...existingSongs, ...kpopSongs];

  // Escribir el nuevo arreglo de vuelta a seed_500_songs.js
  let newSeedContent = seedContent.replace(
    /const songs = (\[[\s\S]*?\]);/,
    `const songs = ${JSON.stringify(mergedSongs, null, 2)};`
  );
  
  fs.writeFileSync(seed500Path, newSeedContent, "utf-8");
  console.log(`✅ seed_500_songs.js actualizado. Total canciones: ${mergedSongs.length}`);
}

run();
